### PR TITLE
Implement User Preferences

### LINKED ISSUE #23: Implement Prompts
Prompts are the forms that users can enter information about themselves on.

### PR DESCRIPTION
**Pull request by katesliang**
## Overview

Implement User Preferences!

## Changes Made

- Modify Person table to include prompt questions and answers
- Include prompts in update user endpoint

## Test Coverage

Manual testing via Postman (see below for example)

## Related PRs or Issues

Closes #23 

Add user preferences via update user endpoint

## api/me/ - POST
**NOTE: When editing user preferences, must include all previous prompts if they remain the same. To reset prompts, set "prompts" to [].

Sample body: 
```
{
     "prompts": [{"id": 1, "answer": "rice cake"}, {"id":2,  "answer": "heat waves"}]
}
```
Sample response:
```
{
    "id": 2,
    "netid": "ksl67",
    "first_name": "Kate",
    "last_name": "Liang",
    "phone_number": "1234567890",
    "grade": "2024",
    "profile_pic_url": null,
    "pronouns": "she/her",
    "prompts": [
        {
            "id": 1,
            "question_name": "Favorite food",
            "question_placeholder": "Ramen",
            "answer": "rice cake"
        },
        {
            "id": 2,
            "question_name": "Favorite song",
            "question_placeholder": "Rich Flex",
            "answer": "heat waves"
        }
    ]
}
```

### CODE REVIEW

**Review by snajima — CHANGES_REQUESTED** [review]
looks good, but why are questions in a list and answers in json format?

**Comment by katesliang** [comment]
@snajima django many-to-many relationships (prompts and users) are represented as querysets (see: https://docs.djangoproject.com/en/4.1/ref/models/querysets/). we represent each user's prompt answers using a string list (which json.dumps() / json.loads()) helps us do. can add comments to clarify this!

**Comment by snajima** [comment]
how exactly are we keeping track of which answers correspond to which questions?

**Comment by katesliang** [comment]
the indices of the prompt questions correspond to the indices of the prompt answers string list

**Review by snajima — APPROVED** [review]
ok, sgtm! does this not have a lot of null space tho? do we have null in place for every question they didn't answer?

**Comment by katesliang** [comment]
there shouldn't be any null space. we have a table for every question. for each question, we store the questions they answered and their answered in the string list.

**Review by joycrwu — APPROVED** [review]

**Pull request merged**
